Added readme.md and тз.md
SergeyKaef/tetris_game pull request #15
Opened 2024-12-05 11:38 UTC by SergeyKaef

2024-12-05 11:39 UTC, Ilua01 reviewed
ok

2024-12-05 11:39 UTC, Anyutka5 reviewed
ok

2024-12-05 12:07 UTC, Laggon requested changes

2024-12-05 12:07 UTC, Laggon commented on README.md
> +-	Платформа: .NET Framework / .NET Core
Это разные технологии, нужно указать итоговый выбор

2024-12-05 12:07 UTC, Laggon commented on README.md
> +- [**Техническое задание**](https://github.com/SergeyKaef/tetris_game/blob/6a70c8f40d8bf8100afcf5f460bac59105136516/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5%20%D0%B7%D0%B0%D
Указать относительную ссылку

2024-12-08 10:20 UTC, Anyutka5 approved these changes

2024-12-08 10:21 UTC, Ilua01 approved these changes

2024-12-08 16:22 UTC, closed without merging