Added documentation
SergeyKaef/tetris_game pull request #17
Opened 2024-12-08 16:25 UTC by SergeyKaef

Added README.md and T3.md

2024-12-14 16:46 UTC, Laggon requested changes
Нужно исправить отставание от основной ветки

2024-12-14 16:47 UTC, Laggon commented
Нужно одобрение от остальных участников проекта

2024-12-14 16:51 UTC, SergeyKaef commented
> Нужно исправить отставание от основной ветки

В основную ветку оно подтянется только после merge? Можете пожалуйста объяснить подробнее?

2024-12-14 17:44 UTC, Laggon commented
> > Нужно исправить отставание от основной ветки
> 
> В основную ветку оно подтянется только после merge. Одобрение запросил.

Отображается лишнее изменение (удаление файла `Техническое задание.md`) во вкладке `Files changed`

2024-12-15 09:07 UTC, SergeyKaef commented
> > > Нужно исправить отставание от основной ветки
> > 
> > 
> > В основную ветку оно подтянется только после merge. Одобрение запросил.
> 
> Отображается лишнее изменение (удаление файла `Техническое задание.md`) во вкладке `Files changed`

Я никак не могу его убрать.
![image](https://github.com/user-attachments/assets/86b0d045-1049-48b7-972a-5c9af5b9d093)
![Снимок экрана 2024-12-15 140531](https://github.com/user-attachments/assets/185eee58-0b5b-470d-bf75-b9339cb06693)
Пишет что нужно перейти на данную ветку, но её не существует.

2024-12-16 05:10 UTC, Ilua01 approved these changes

2024-12-16 05:13 UTC, Anyutka5 approved these changes

2024-12-16 08:54 UTC, Laggon commented
Нужно выполнить слияние из основной ветки

Например по [данной инструкции](https://github.com/Laggon/docs/blob/main/merge/index.md)

2024-12-16 08:54 UTC, Laggon commented
> > > > Нужно исправить отставание от основной ветки
> > > 
> > > 
> > > В основную ветку оно подтянется только после merge. Одобрение запросил.
> > 
> > 
> > Отображается лишнее изменение (удаление файла `Техническое задание.md`) во вкладке `Files changed`
> 
> Я никак не могу его убрать. ![image](https://private-user-images.githubusercontent.com/96934937/395844162-86b0d045-1049-48b7-972a-5c9af5b9d093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzk0OTgsIm5iZiI6MTczNDMzOTE5OCwicGF0aCI6Ii85NjkzNDkzNy8zOTU4NDQxNjItODZiMGQwNDUtMTA0OS00OGI3LTk3MmEtNWM5YWY1YjlkMDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA4NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViM2RlZjc3MWU1YTQ2NzVjYTZjMWY4ODg2N2VkMTc2OWJlNjdlZjJkMDQ2YzZjNzI5OGMzMTljYmU4MzA1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eqmGLbsBLADMEw2_vQZrWyFfTFhq7QXZnG-HtMUnGtQ) ![Снимок экрана 2024-12-15 140531](https://private-user-images.githubusercontent.com/96934937/395844234-185eee58-0b5b-470d-bf75-b9339cb06693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzk0OTgsIm5iZiI6MTczNDMzOTE5OCwicGF0aCI6Ii85NjkzNDkzNy8zOTU4NDQyMzQtMTg1ZWVlNTgtMGI1Yi00NzBkLWJmNzUtYjkzMzljYjA2NjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA4NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMTVhOTViNDhmZmVhNWI4ZTczZjdkYTg2ZTgwMDU3ZWVmYWE4MTNmNGI3NjkxMmE4MTk3NWNiNWVlMGNhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ex40HcSKhXI8lCcg_BuQr0Ma3WrNY_xfafnyNneuCzw) Пишет что нужно перейти на данную ветку, но её не существует.

Нужно выполнить слияние из основной ветки

Например по [данной инструкции](https://github.com/Laggon/docs/blob/main/merge/index.md)

2024-12-16 09:23 UTC, SergeyKaef commented
> > > > > Нужно исправить отставание от основной ветки
> > > > 
> > > > 
> > > > В основную ветку оно подтянется только после merge. Одобрение запросил.
> > > 
> > > 
> > > Отображается лишнее изменение (удаление файла `Техническое задание.md`) во вкладке `Files changed`
> > 
> > 
> > Я никак не могу его убрать. ![image](https://private-user-images.githubusercontent.com/96934937/395844162-86b0d045-1049-48b7-972a-5c9af5b9d093.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzk0OTgsIm5iZiI6MTczNDMzOTE5OCwicGF0aCI6Ii85NjkzNDkzNy8zOTU4NDQxNjItODZiMGQwNDUtMTA0OS00OGI3LTk3MmEtNWM5YWY1YjlkMDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA4NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViM2RlZjc3MWU1YTQ2NzVjYTZjMWY4ODg2N2VkMTc2OWJlNjdlZjJkMDQ2YzZjNzI5OGMzMTljYmU4MzA1ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eqmGLbsBLADMEw2_vQZrWyFfTFhq7QXZnG-HtMUnGtQ) ![Снимок экрана 2024-12-15 140531](https://private-user-images.githubusercontent.com/96934937/395844234-185eee58-0b5b-470d-bf75-b9339cb06693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzk0OTgsIm5iZiI6MTczNDMzOTE5OCwicGF0aCI6Ii85NjkzNDkzNy8zOTU4NDQyMzQtMTg1ZWVlNTgtMGI1Yi00NzBkLWJmNzUtYjkzMzljYjA2NjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA4NTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMTVhOTViNDhmZmVhNWI4ZTczZjdkYTg2ZTgwMDU3ZWVmYWE4MTNmNGI3NjkxMmE4MTk3NWNiNWVlMGNhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ex40HcSKhXI8lCcg_BuQr0Ma3WrNY_xfafnyNneuCzw) Пишет что нужно перейти на данную ветку, но её не существует.
> 
> Нужно выполнить слияние из основной ветки
> 
> Например по [данной инструкции](https://github.com/Laggon/docs/blob/main/merge/index.md)

Исправлено

2024-12-19 06:44 UTC, Laggon approved these changes

2024-12-19 06:46 UTC, merged